fix(charts/cloudflare-tunnel-remote): remove invalid secret ref key
cloudflare/helm-charts pull request #47
Opened 2023-08-11 16:00 UTC by uhthomas

It is not valid to specify individual keys with 'envFrom'. Instead, create environment variables for all secret key value pairs.

Fixes: #46

2023-08-20 23:09 UTC, denzhel commented
Can you please merge this ?

2023-08-21 15:36 UTC, uhthomas commented
Looks like @obezuk is out of office for another couple of weeks. Will ask around and see if anyone else can merge this.

2023-08-21 16:04 UTC, jcsf requested changes

2023-08-21 17:40 UTC, uhthomas commented on charts/cloudflare-tunnel-remote/templates/deployment.yaml
>              name: {{ include "cloudflare-tunnel-remote.fullname" . }}
I had the same thought and that was initially what I was going to do, but wrote it this way purposefully as it seemed to be closer to what the author intended. Happy to make this change though. Give me a second.

2023-08-21 18:20 UTC, jcsf approved these changes

2023-08-22 14:46 UTC, chungthuang approved these changes

2023-08-23 21:12 UTC, denzhel commented
Please merge :) ?

2023-08-24 04:50 UTC, evfurman commented
Can we please get this merged? 🙏

2023-08-28 05:53 UTC, denzhel commented
Can we get this merged please ?

2023-08-29 21:23 UTC, tvarney approved these changes

2023-08-29 21:36 UTC, larcher approved these changes

2023-08-29 21:36 UTC, merged